[package]
name = "gg_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
clap = { version = "3.0.0-beta.5", features = ["derive"] }  # 命令行解析
regex = "1.5.4"